# Generated by Django 2.0.13 on 2019-03-30 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('SC', 'SC'), ('SS', 'SS'), ('MA', 'MA'), ('EN', 'EN'), ('KA', 'KA'), ('EC', 'EC'), ('HI', 'HI'), ('SG', 'SG'), ('SP', 'SP')], max_length=3)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
