# Generated by Django 2.0.13 on 2019-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20190330_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.CharField(default='12.3052032,76.6222336', max_length=100),
        ),
    ]
