# Generated by Django 2.0.13 on 2019-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='credentials',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
